trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerPlatformToolInstaller@2
  inputs:
    DefaultVersion: true
- task: PowerPlatformExportSolution@2
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'PRO-TC-PP_ALM-DEMO'
    SolutionName: 'cargill_test_solution_v01'
    SolutionOutputFile: '$(Build.ArtifactStagingDirectory)\$(SolutionName).zip' 
    AsyncOperation: true
    MaxAsyncWaitTime: '60'
- task: PowerPlatformUnpackSolution@2
  inputs:
    SolutionInputFile: '$(Build.ArtifactStagingDirectory)\$(SolutionName).zip'
    SolutionTargetFolder: '$(Build.SourcesDirectory)\$(SolutionName)'
- task: CmdLine@2
  inputs:
    script: |
      echo "commit all changes"
      git config user.email "powerappsTools@protiviti.net"
      git config user.name "PowerPlatformBuildTools"
      git checkout main
      git pull
      git add .
      git commit -m "$(SolutionName) Exported"
      
      echo "push code to new repo"
      git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push origin HEAD:main
    
    displayName: 'Git Commit Solution to Repo'